### PR TITLE
Happy Numbers from Tobias Muench

### PR DESCRIPTION
**Pull request by tomuench**
Hey,
have played a bit Codegolf Today. I have only counted the characters in the function.
Maybe you want to check.
Cheers!

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
Sorry for my late response and thanks for your PR :)
However, there are some problems with the pull request:

* There are many temporary/useless/unwanted files in your commits, for example: `.rspec`, `Gemfile` and `Gemfile.lock`. When solving small tasks like "happy number", please add just one file instead of a complete project structure. So please remove the `.gitignore` files too.
* Tests, while always nice to have, are not really necessary here. Also as @JulianKniephoff pointed out, those tests aren't really idiomatic. Maybe he can tell you more about it. 

I'd be delighted if you'd fix your PR and I could merge it ;)

**Comment by JulianKniephoff** [comment]
The commit history should be consistent. For `happy_number`, there is a commit updating the highscores, for `is_prime`, there is not.

Also what I object to in the tests is the naming. `it`-blocks are called like that for a reason. Here is an idomatic example:

```ruby
it 'should accept primes` do
  # ...
end
```
but I would just leave out the tests.

**Comment by tomuench** [comment]
@LukasKalbertodt : Removed the whole project and extracted the relevant files.
@JulianKniephoff : You're right. I have worked a bit fast, so the test naming was not correct at all. I removed the unit-tests as well, but i thought they were useful.

Hope now is the code allright!

**Comment by LukasKalbertodt** [comment]
Yep, code looks good :smile_cat:  However, the commit history is a bit fucked up...
To fix it you could "combine" all your commits into two new commits (one for primes, one for happy). This can be done by:


```
git reset HEAD~5
git add happy_number/README.md happy_number/happyNumberRuby_69chars.rb
git commit
git add is_prime/README.md is_prime/ruby_41chars.rb
git commit
git push --force origin master 
```

**Pull request closed without merging**
